apiVersion: v1
kind: Service
metadata:
  name: springboot-web-postgres-svc
spec:
  selector:
    app: springboot-web-postgres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort